import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { useAuth } from '@/hooks/useAuth';
import { 
  HeartHandshake, 
  Target, 
  Brain, 
  TrendingUp, 
  Users, 
  Shield,
  ArrowRight 
} from 'lucide-react';

const Index = () => {
  const { user, loading } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!loading && user) {
      // User is logged in, redirect to goal selection
      navigate('/goal-selection');
    }
  }, [user, loading, navigate]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-background via-background-soft to-background flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background-soft to-background">
      {/* Hero Section */}
      <div className="relative overflow-hidden">
        <div className="max-w-6xl mx-auto px-4 py-20">
          <div className="text-center space-y-8">
            <div className="space-y-4">
              <div className="flex justify-center">
                <div className="gradient-bg p-4 rounded-full floating-animation">
                  <HeartHandshake className="h-12 w-12 text-white" />
                </div>
              </div>
              <h1 className="text-5xl md:text-6xl font-bold gradient-text">
                CalorieWise
              </h1>
              <p className="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto">
                Your intelligent nutrition companion for personalized weight management and healthy living
              </p>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                size="lg" 
                className="gradient-bg hover:opacity-90 transition-opacity text-lg px-8 py-6"
                onClick={() => navigate('/auth')}
              >
                Get Started
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              <Button 
                size="lg" 
                variant="outline" 
                className="text-lg px-8 py-6 border-primary/30 hover:bg-primary/5"
                onClick={() => navigate('/auth')}
              >
                Sign In
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="max-w-6xl mx-auto px-4 py-16">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold gradient-text mb-4">
            Why Choose CalorieWise?
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Science-backed nutrition planning powered by AI for sustainable results
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <Card className="health-card slide-up">
            <CardHeader>
              <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                <Target className="h-6 w-6 text-primary" />
              </div>
              <CardTitle>Personalized Goals</CardTitle>
              <CardDescription>
                Set and track weight loss or weight gain goals tailored to your lifestyle and preferences
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="health-card slide-up" style={{ animationDelay: '0.1s' }}>
            <CardHeader>
              <div className="w-12 h-12 bg-secondary/10 rounded-lg flex items-center justify-center mb-4">
                <Brain className="h-6 w-6 text-secondary" />
              </div>
              <CardTitle>AI-Powered Plans</CardTitle>
              <CardDescription>
                Get customized meal plans generated by advanced AI based on your dietary preferences and goals
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="health-card slide-up" style={{ animationDelay: '0.2s' }}>
            <CardHeader>
              <div className="w-12 h-12 bg-accent/10 rounded-lg flex items-center justify-center mb-4">
                <TrendingUp className="h-6 w-6 text-accent" />
              </div>
              <CardTitle>Progress Tracking</CardTitle>
              <CardDescription>
                Monitor your journey with comprehensive tracking and analytics to stay motivated
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="health-card slide-up" style={{ animationDelay: '0.3s' }}>
            <CardHeader>
              <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                <Users className="h-6 w-6 text-primary" />
              </div>
              <CardTitle>Diet Flexibility</CardTitle>
              <CardDescription>
                Support for vegetarian, non-vegetarian, and vegan diets with culturally diverse meal options
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="health-card slide-up" style={{ animationDelay: '0.4s' }}>
            <CardHeader>
              <div className="w-12 h-12 bg-secondary/10 rounded-lg flex items-center justify-center mb-4">
                <Shield className="h-6 w-6 text-secondary" />
              </div>
              <CardTitle>Science-Based</CardTitle>
              <CardDescription>
                All recommendations are based on proven nutritional science and metabolic calculations
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="health-card slide-up" style={{ animationDelay: '0.5s' }}>
            <CardHeader>
              <div className="w-12 h-12 bg-accent/10 rounded-lg flex items-center justify-center mb-4">
                <HeartHandshake className="h-6 w-6 text-accent" />
              </div>
              <CardTitle>Sustainable Habits</CardTitle>
              <CardDescription>
                Focus on building long-term healthy habits rather than quick fixes for lasting results
              </CardDescription>
            </CardHeader>
          </Card>
        </div>
      </div>

      {/* CTA Section */}
      <div className="bg-gradient-to-r from-primary/10 via-secondary/10 to-accent/10 border-y">
        <div className="max-w-4xl mx-auto px-4 py-16 text-center space-y-8">
          <h2 className="text-3xl md:text-4xl font-bold gradient-text">
            Ready to Transform Your Health?
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Join thousands of users who have achieved their health goals with CalorieWise's 
            personalized nutrition plans.
          </p>
          <Button 
            size="lg" 
            className="gradient-bg hover:opacity-90 transition-opacity text-lg px-8 py-6"
            onClick={() => navigate('/auth')}
          >
            Start Your Journey Today
            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-background/80 backdrop-blur-sm border-t">
        <div className="max-w-6xl mx-auto px-4 py-8">
          <div className="text-center space-y-4">
            <div className="flex justify-center">
              <div className="gradient-bg p-2 rounded-lg">
                <HeartHandshake className="h-6 w-6 text-white" />
              </div>
            </div>
            <h3 className="text-lg font-bold gradient-text">CalorieWise</h3>
            <p className="text-sm text-muted-foreground">
              Your intelligent nutrition companion for a healthier lifestyle.
            </p>
            <p className="text-xs text-muted-foreground">
              © 2024 CalorieWise. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Index;
